// Exports des domaines spécifiques
export * from './actor.js'
export * from './audit_log.js'
export * from './auth.js'
export * from './calendar.js'
export * from './campaign.js'
export * from './convention.js'
export * from './document.js'
export * from './location.js'
export * from './parcel.js'
export * from './product_transfer.js'
export * from './production_basin.js'
export * from './store.js'
export * from './sync.js'
export * from './system.js'
export * from './transaction.js'
export * from './user.js'
export * from './validation.js'

// Re-export des enums principaux pour la compatibilité
import { ActorErrorCodes, ActorSuccessCodes } from './actor.js'
import { AuditLogErrorCodes, AuditLogSuccessCodes } from './audit_log.js'
import { AuthErrorCodes, AuthSuccessCodes } from './auth.js'
import { CalendarErrorCodes, CalendarSuccessCodes } from './calendar.js'
import { CampaignErrorCodes, CampaignSuccessCodes } from './campaign.js'
import { ConventionErrorCodes, ConventionSuccessCodes } from './convention.js'
import { DocumentErrorCodes, DocumentSuccessCodes } from './document.js'
import { LocationErrorCodes, LocationSuccessCodes } from './location.js'
import { ParcelErrorCodes, ParcelSuccessCodes } from './parcel.js'
import { ProductTransferErrorCodes, ProductTransferSuccessCodes } from './product_transfer.js'
import { ProductionBasinErrorCodes, ProductionBasinSuccessCodes } from './production_basin.js'
import { StoreErrorCodes, StoreSuccessCodes } from './store.js'
import { SyncErrorCodes, SyncSuccessCodes } from './sync.js'
import { SystemErrorCodes } from './system.js'
import { TransactionErrorCodes, TransactionSuccessCodes } from './transaction.js'
import { UserErrorCodes, UserSuccessCodes } from './user.js'
import { ValidationErrorCodes } from './validation.js'

/**
 * Enum unifié des codes d'erreur pour la compatibilité avec l'ancien système
 */
export enum ErrorCodes {
  // Acteurs
  ACTOR_NOT_FOUND = ActorErrorCodes.ACTOR_NOT_FOUND,
  ACTOR_LIST_FAILED = ActorErrorCodes.ACTOR_LIST_FAILED,
  ACTOR_CREATION_FAILED = ActorErrorCodes.ACTOR_CREATION_FAILED,
  ACTOR_UPDATE_FAILED = ActorErrorCodes.ACTOR_UPDATE_FAILED,
  ACTOR_DELETION_FAILED = ActorErrorCodes.ACTOR_DELETION_FAILED,
  ACTOR_ACTIVATION_FAILED = ActorErrorCodes.ACTOR_ACTIVATION_FAILED,
  ACTOR_DEACTIVATION_FAILED = ActorErrorCodes.ACTOR_DEACTIVATION_FAILED,
  ACTOR_STATUS_UPDATE_FAILED = ActorErrorCodes.ACTOR_STATUS_UPDATE_FAILED,
  ACTOR_NOT_AUTHORIZED = ActorErrorCodes.ACTOR_NOT_AUTHORIZED,
  ACTOR_ONCC_ID_EXISTS = ActorErrorCodes.ACTOR_ONCC_ID_EXISTS,
  ACTOR_IDENTIFIANT_EXISTS = ActorErrorCodes.ACTOR_IDENTIFIANT_EXISTS,
  ACTOR_ALREADY_ACTIVE = ActorErrorCodes.ACTOR_ALREADY_ACTIVE,
  ACTOR_ALREADY_INACTIVE = ActorErrorCodes.ACTOR_ALREADY_INACTIVE,
  ACTOR_HAS_USERS = ActorErrorCodes.ACTOR_HAS_USERS,
  ACTOR_MANAGER_INFO_REQUIRED = ActorErrorCodes.ACTOR_MANAGER_INFO_REQUIRED,
  ACTOR_EMAIL_OR_PHONE_REQUIRED = ActorErrorCodes.ACTOR_EMAIL_OR_PHONE_REQUIRED,
  ACTOR_NOT_OPA = ActorErrorCodes.ACTOR_NOT_OPA,
  ACTOR_NOT_PRODUCER = ActorErrorCodes.ACTOR_NOT_PRODUCER,
  ACTOR_NOT_BUYER = ActorErrorCodes.ACTOR_NOT_BUYER,
  ACTOR_NOT_EXPORTER = ActorErrorCodes.ACTOR_NOT_EXPORTER,
  PRODUCER_ALREADY_IN_OPA = ActorErrorCodes.PRODUCER_ALREADY_IN_OPA,
  PRODUCER_NOT_IN_OPA = ActorErrorCodes.PRODUCER_NOT_IN_OPA,
  ADD_PRODUCER_TO_OPA_FAILED = ActorErrorCodes.ADD_PRODUCER_TO_OPA_FAILED,
  REMOVE_PRODUCER_FROM_OPA_FAILED = ActorErrorCodes.REMOVE_PRODUCER_FROM_OPA_FAILED,
  BUYER_ALREADY_IN_EXPORTER = ActorErrorCodes.BUYER_ALREADY_IN_EXPORTER,
  BUYER_ALREADY_ASSIGNED_TO_OTHER_EXPORTER = ActorErrorCodes.BUYER_ALREADY_ASSIGNED_TO_OTHER_EXPORTER,
  BUYER_NOT_IN_EXPORTER = ActorErrorCodes.BUYER_NOT_IN_EXPORTER,
  ADD_BUYER_TO_EXPORTER_FAILED = ActorErrorCodes.ADD_BUYER_TO_EXPORTER_FAILED,
  REMOVE_BUYER_FROM_EXPORTER_FAILED = ActorErrorCodes.REMOVE_BUYER_FROM_EXPORTER_FAILED,
  NO_ACTIVE_CAMPAIGN = ActorErrorCodes.NO_ACTIVE_CAMPAIGN,
  ACTOR_SYNC_FAILED = ActorErrorCodes.ACTOR_SYNC_FAILED,
  ACTOR_MISSING_REQUIRED_DOCUMENTS = ActorErrorCodes.ACTOR_MISSING_REQUIRED_DOCUMENTS,

  // Audit Logs
  AUDIT_LOG_LIST_FAILED = AuditLogErrorCodes.AUDIT_LOG_LIST_FAILED,
  AUDIT_LOG_NOT_FOUND = AuditLogErrorCodes.AUDIT_LOG_NOT_FOUND,
  AUDIT_LOG_DETAILS_FAILED = AuditLogErrorCodes.AUDIT_LOG_DETAILS_FAILED,
  AUDIT_LOG_STATS_FAILED = AuditLogErrorCodes.AUDIT_LOG_STATS_FAILED,
  AUDIT_LOG_INVALID_AUDITABLE_TYPE = AuditLogErrorCodes.AUDIT_LOG_INVALID_AUDITABLE_TYPE,
  AUDIT_LOG_INVALID_AUDITABLE_ID = AuditLogErrorCodes.AUDIT_LOG_INVALID_AUDITABLE_ID,
  AUDIT_LOG_INVALID_PAGINATION = AuditLogErrorCodes.AUDIT_LOG_INVALID_PAGINATION,
  AUDIT_LOG_ACCESS_DENIED = AuditLogErrorCodes.AUDIT_LOG_ACCESS_DENIED,
  AUDIT_LOG_NOT_AUTHORIZED = AuditLogErrorCodes.AUDIT_LOG_NOT_AUTHORIZED,

  // Authentification
  AUTH_LOGIN_INVALID_CREDENTIALS = AuthErrorCodes.LOGIN_INVALID_CREDENTIALS,
  AUTH_LOGIN_ACCOUNT_INACTIVE = AuthErrorCodes.LOGIN_ACCOUNT_INACTIVE,
  AUTH_LOGIN_ACTOR_INACTIVE = AuthErrorCodes.LOGIN_ACTOR_INACTIVE,
  AUTH_LOGIN_ACCOUNT_BLOCKED = AuthErrorCodes.LOGIN_ACCOUNT_BLOCKED,
  AUTH_LOGIN_DEFAULT_PASSWORD = AuthErrorCodes.LOGIN_DEFAULT_PASSWORD,
  AUTH_LOGIN_FAILED = AuthErrorCodes.LOGIN_FAILED,
  AUTH_OTP_INVALID = AuthErrorCodes.OTP_INVALID,
  AUTH_OTP_EXPIRED = AuthErrorCodes.OTP_EXPIRED,
  AUTH_OTP_SESSION_INVALID = AuthErrorCodes.OTP_SESSION_INVALID,
  AUTH_OTP_SEND_FAILED = AuthErrorCodes.OTP_SEND_FAILED,
  AUTH_OTP_VERIFY_FAILED = AuthErrorCodes.OTP_VERIFY_FAILED,
  AUTH_PASSWORD_CHANGE_CURRENT_INVALID = AuthErrorCodes.PASSWORD_CHANGE_CURRENT_INVALID,
  AUTH_PASSWORD_CHANGE_FAILED = AuthErrorCodes.PASSWORD_CHANGE_FAILED,
  AUTH_PASSWORD_RESET_TOKEN_INVALID = AuthErrorCodes.PASSWORD_RESET_TOKEN_INVALID,
  AUTH_PASSWORD_RESET_TOKEN_EXPIRED = AuthErrorCodes.PASSWORD_RESET_TOKEN_EXPIRED,
  AUTH_PASSWORD_RESET_FAILED = AuthErrorCodes.PASSWORD_RESET_FAILED,
  AUTH_PASSWORD_FORGOT_EMAIL_NOT_FOUND = AuthErrorCodes.PASSWORD_FORGOT_EMAIL_NOT_FOUND,
  AUTH_PASSWORD_FORGOT_SEND_FAILED = AuthErrorCodes.PASSWORD_FORGOT_SEND_FAILED,
  AUTH_SECURITY_QUESTIONS_INVALID_ANSWERS = AuthErrorCodes.SECURITY_QUESTIONS_INVALID_ANSWERS,
  AUTH_SECURITY_QUESTIONS_NOT_FOUND = AuthErrorCodes.SECURITY_QUESTIONS_NOT_FOUND,
  AUTH_SECURITY_QUESTIONS_SETUP_FAILED = AuthErrorCodes.SECURITY_QUESTIONS_SETUP_FAILED,
  AUTH_INIT_TOKEN_INVALID = AuthErrorCodes.INIT_TOKEN_INVALID,
  AUTH_INIT_TOKEN_EXPIRED = AuthErrorCodes.INIT_TOKEN_EXPIRED,
  AUTH_INIT_FAILED = AuthErrorCodes.INIT_FAILED,
  AUTH_SESSION_EXPIRED = AuthErrorCodes.SESSION_EXPIRED,
  AUTH_SESSION_INVALID = AuthErrorCodes.SESSION_INVALID,
  AUTH_TOKEN_INVALID = AuthErrorCodes.TOKEN_INVALID,
  AUTH_TOKEN_EXPIRED = AuthErrorCodes.TOKEN_EXPIRED,
  AUTH_LOGOUT_FAILED = AuthErrorCodes.LOGOUT_FAILED,

  // Calendriers
  CALENDAR_NOT_FOUND = CalendarErrorCodes.NOT_FOUND,
  CALENDAR_LIST_FAILED = CalendarErrorCodes.LIST_FAILED,
  CALENDAR_SHOW_FAILED = CalendarErrorCodes.SHOW_FAILED,
  CALENDAR_CREATE_FAILED = CalendarErrorCodes.CREATE_FAILED,
  CALENDAR_CODE_EXISTS = CalendarErrorCodes.CODE_EXISTS,
  CALENDAR_CAMPAIGN_NOT_FOUND = CalendarErrorCodes.CAMPAIGN_NOT_FOUND,
  CALENDAR_CONVENTION_NOT_FOUND = CalendarErrorCodes.CONVENTION_NOT_FOUND,
  CALENDAR_CONVENTION_REQUIRED = CalendarErrorCodes.CONVENTION_REQUIRED,
  CALENDAR_OPA_NOT_FOUND = CalendarErrorCodes.OPA_NOT_FOUND,
  CALENDAR_OPA_NOT_ACTIVE = CalendarErrorCodes.OPA_NOT_ACTIVE,
  CALENDAR_INVALID_DATE_RANGE = CalendarErrorCodes.INVALID_DATE_RANGE,
  CALENDAR_DATE_OVERLAP = CalendarErrorCodes.DATE_OVERLAP,
  CALENDAR_INVALID_CALENDAR_TYPE = CalendarErrorCodes.INVALID_CALENDAR_TYPE,
  CALENDAR_UPDATE_FAILED = CalendarErrorCodes.UPDATE_FAILED,
  CALENDAR_UPDATE_CODE_EXISTS = CalendarErrorCodes.UPDATE_CODE_EXISTS,
  CALENDAR_UPDATE_NOT_AUTHORIZED = CalendarErrorCodes.UPDATE_NOT_AUTHORIZED,
  CALENDAR_STATUS_UPDATE_INVALID = CalendarErrorCodes.STATUS_UPDATE_INVALID,
  CALENDAR_STATUS_UPDATE_FAILED = CalendarErrorCodes.STATUS_UPDATE_FAILED,
  CALENDAR_CODE_MISMATCH = CalendarErrorCodes.CODE_MISMATCH,
  CALENDAR_PAST_DATE_STATUS_CHANGE = CalendarErrorCodes.PAST_DATE_STATUS_CHANGE,
  CALENDAR_DELETE_FAILED = CalendarErrorCodes.DELETE_FAILED,
  CALENDAR_DELETE_NOT_AUTHORIZED = CalendarErrorCodes.DELETE_NOT_AUTHORIZED,
  CALENDAR_AUDIT_HISTORY_FAILED = CalendarErrorCodes.AUDIT_HISTORY_FAILED,
  CALENDAR_SYNC_FAILED = CalendarErrorCodes.SYNC_FAILED,

  // Utilisateurs
  USER_CREATE_EMAIL_EXISTS = UserErrorCodes.CREATE_EMAIL_EXISTS,
  USER_CREATE_PSEUDO_EXISTS = UserErrorCodes.CREATE_PSEUDO_EXISTS,
  USER_CREATE_BASSIN_NOT_FOUND = UserErrorCodes.CREATE_BASSIN_NOT_FOUND,
  USER_CREATE_BASSIN_REQUIRED = UserErrorCodes.CREATE_BASSIN_REQUIRED,
  USER_CREATE_EMAIL_SEND_FAILED = UserErrorCodes.CREATE_EMAIL_SEND_FAILED,
  USER_CREATE_FAILED = UserErrorCodes.CREATE_FAILED,
  USER_NOT_FOUND = UserErrorCodes.NOT_FOUND,
  USER_LIST_FAILED = UserErrorCodes.LIST_FAILED,
  USER_UPDATE_EMAIL_EXISTS = UserErrorCodes.UPDATE_EMAIL_EXISTS,
  USER_UPDATE_PSEUDO_EXISTS = UserErrorCodes.UPDATE_PSEUDO_EXISTS,
  USER_UPDATE_NOT_AUTHORIZED = UserErrorCodes.UPDATE_NOT_AUTHORIZED,
  USER_UPDATE_ACTOR_MANAGER_RESTRICTED = UserErrorCodes.UPDATE_ACTOR_MANAGER_RESTRICTED,
  USER_UPDATE_FAILED = UserErrorCodes.UPDATE_FAILED,
  USER_STATUS_UPDATE_INVALID = UserErrorCodes.STATUS_UPDATE_INVALID,
  USER_STATUS_UPDATE_FAILED = UserErrorCodes.STATUS_UPDATE_FAILED,
  USER_DELETE_NOT_AUTHORIZED = UserErrorCodes.DELETE_NOT_AUTHORIZED,
  USER_DELETE_FAILED = UserErrorCodes.DELETE_FAILED,
  USER_PASSWORD_RESET_FAILED = UserErrorCodes.PASSWORD_RESET_FAILED,
  USER_PASSWORD_RESET_EMAIL_SEND_FAILED = UserErrorCodes.PASSWORD_RESET_EMAIL_SEND_FAILED,
  USER_AUDIT_HISTORY_FAILED = UserErrorCodes.AUDIT_HISTORY_FAILED,

  // Validation
  VALIDATION_REQUIRED_FIELD_MISSING = ValidationErrorCodes.REQUIRED_FIELD_MISSING,
  VALIDATION_INVALID_FORMAT = ValidationErrorCodes.INVALID_FORMAT,
  VALIDATION_INVALID_LENGTH = ValidationErrorCodes.INVALID_LENGTH,
  VALIDATION_INVALID_EMAIL = ValidationErrorCodes.INVALID_EMAIL,
  VALIDATION_INVALID_PHONE = ValidationErrorCodes.INVALID_PHONE,
  VALIDATION_INVALID_PASSWORD_FORMAT = ValidationErrorCodes.INVALID_PASSWORD_FORMAT,
  VALIDATION_PASSWORD_CONFIRMATION_MISMATCH = ValidationErrorCodes.PASSWORD_CONFIRMATION_MISMATCH,
  VALIDATION_INVALID_ROLE = ValidationErrorCodes.INVALID_ROLE,
  VALIDATION_INVALID_LANGUAGE = ValidationErrorCodes.INVALID_LANGUAGE,
  VALIDATION_INVALID_STATUS = ValidationErrorCodes.INVALID_STATUS,
  VALIDATION_FAILED = ValidationErrorCodes.FAILED,
  VALIDATION_INVALID_OTP_FORMAT = ValidationErrorCodes.INVALID_OTP_FORMAT,
  VALIDATION_INVALID_TOKEN_FORMAT = ValidationErrorCodes.INVALID_TOKEN_FORMAT,
  VALIDATION_INVALID_UUID_FORMAT = ValidationErrorCodes.INVALID_UUID_FORMAT,

  // Système
  SYSTEM_INTERNAL_ERROR = SystemErrorCodes.INTERNAL_ERROR,
  SYSTEM_DATABASE_ERROR = SystemErrorCodes.DATABASE_ERROR,
  SYSTEM_REDIS_ERROR = SystemErrorCodes.REDIS_ERROR,
  SYSTEM_EMAIL_SERVICE_ERROR = SystemErrorCodes.EMAIL_SERVICE_ERROR,
  SYSTEM_EXTERNAL_SERVICE_ERROR = SystemErrorCodes.EXTERNAL_SERVICE_ERROR,
  SYSTEM_UNAUTHORIZED = SystemErrorCodes.UNAUTHORIZED,
  SYSTEM_FORBIDDEN = SystemErrorCodes.FORBIDDEN,
  SYSTEM_RATE_LIMITED = SystemErrorCodes.RATE_LIMITED,
  SYSTEM_CONFIG_ERROR = SystemErrorCodes.CONFIG_ERROR,
  SYSTEM_SERVICE_UNAVAILABLE = SystemErrorCodes.SERVICE_UNAVAILABLE,

  // Localisations
  LOCATION_NOT_FOUND = LocationErrorCodes.NOT_FOUND,
  LOCATION_LIST_FAILED = LocationErrorCodes.LIST_FAILED,
  LOCATION_HIERARCHY_FAILED = LocationErrorCodes.HIERARCHY_FAILED,
  LOCATION_CHILDREN_FAILED = LocationErrorCodes.CHILDREN_FAILED,

  // Parcelles
  PARCEL_NOT_FOUND = ParcelErrorCodes.PARCEL_NOT_FOUND,
  PARCEL_LIST_FAILED = ParcelErrorCodes.PARCEL_LIST_FAILED,
  PARCEL_CREATION_FAILED = ParcelErrorCodes.PARCEL_CREATION_FAILED,
  PARCEL_UPDATE_FAILED = ParcelErrorCodes.PARCEL_UPDATE_FAILED,
  PARCEL_DELETION_FAILED = ParcelErrorCodes.PARCEL_DELETION_FAILED,
  PARCEL_ACTIVATION_FAILED = ParcelErrorCodes.PARCEL_ACTIVATION_FAILED,
  PARCEL_DEACTIVATION_FAILED = ParcelErrorCodes.PARCEL_DEACTIVATION_FAILED,
  PARCEL_NOT_AUTHORIZED = ParcelErrorCodes.PARCEL_NOT_AUTHORIZED,
  PARCEL_ONCC_ID_EXISTS = ParcelErrorCodes.PARCEL_ONCC_ID_EXISTS,
  PARCEL_IDENTIFICATION_ID_EXISTS = ParcelErrorCodes.PARCEL_IDENTIFICATION_ID_EXISTS,
  PARCEL_COORDINATES_FAILED = ParcelErrorCodes.PARCEL_COORDINATES_FAILED,
  PARCEL_COORDINATES_INVALID = ParcelErrorCodes.PARCEL_COORDINATES_INVALID,
  PARCEL_STATS_FAILED = ParcelErrorCodes.PARCEL_STATS_FAILED,
  PARCEL_PRODUCER_NOT_FOUND = ParcelErrorCodes.PARCEL_PRODUCER_NOT_FOUND,
  PARCEL_PRODUCER_INVALID = ParcelErrorCodes.PARCEL_PRODUCER_INVALID,
  PARCEL_VALIDATION_FAILED = ParcelErrorCodes.PARCEL_VALIDATION_FAILED,
  PARCEL_DUPLICATE_IDENTIFIERS = ParcelErrorCodes.PARCEL_DUPLICATE_IDENTIFIERS,
  PARCEL_REQUIRED_FOR_PRODUCER = ParcelErrorCodes.PARCEL_REQUIRED_FOR_PRODUCER,

  // Bassins de production
  PRODUCTION_BASIN_LIST_FAILED = ProductionBasinErrorCodes.LIST_FAILED,
  PRODUCTION_BASIN_NOT_FOUND = ProductionBasinErrorCodes.NOT_FOUND,
  PRODUCTION_BASIN_CREATE_NOT_AUTHORIZED = ProductionBasinErrorCodes.CREATE_NOT_AUTHORIZED,
  PRODUCTION_BASIN_CREATE_FAILED = ProductionBasinErrorCodes.CREATE_FAILED,
  PRODUCTION_BASIN_LOCATION_CONFLICTS = ProductionBasinErrorCodes.LOCATION_CONFLICTS,
  PRODUCTION_BASIN_LOCATION_VALIDATION_FAILED = ProductionBasinErrorCodes.LOCATION_VALIDATION_FAILED,
  PRODUCTION_BASIN_REGION_DEPARTMENT_HIERARCHY_CONFLICT = ProductionBasinErrorCodes.REGION_DEPARTMENT_HIERARCHY_CONFLICT,
  PRODUCTION_BASIN_DEPARTMENT_DISTRICT_HIERARCHY_CONFLICT = ProductionBasinErrorCodes.DEPARTMENT_DISTRICT_HIERARCHY_CONFLICT,
  PRODUCTION_BASIN_DISTRICT_PARENT_CONFLICT = ProductionBasinErrorCodes.DISTRICT_PARENT_CONFLICT,
  PRODUCTION_BASIN_DEPARTMENT_PARENT_CONFLICT = ProductionBasinErrorCodes.DEPARTMENT_PARENT_CONFLICT,
  PRODUCTION_BASIN_DISTRICT_SIBLING_CONFLICT = ProductionBasinErrorCodes.DISTRICT_SIBLING_CONFLICT,
  PRODUCTION_BASIN_UPDATE_FAILED = ProductionBasinErrorCodes.UPDATE_FAILED,
  PRODUCTION_BASIN_DELETE_NOT_AUTHORIZED = ProductionBasinErrorCodes.DELETE_NOT_AUTHORIZED,
  PRODUCTION_BASIN_DELETE_HAS_USERS = ProductionBasinErrorCodes.DELETE_HAS_USERS,
  PRODUCTION_BASIN_DELETE_FAILED = ProductionBasinErrorCodes.DELETE_FAILED,
  PRODUCTION_BASIN_ASSIGN_USERS_NOT_AUTHORIZED = ProductionBasinErrorCodes.ASSIGN_USERS_NOT_AUTHORIZED,
  PRODUCTION_BASIN_ASSIGN_USERS_FAILED = ProductionBasinErrorCodes.ASSIGN_USERS_FAILED,
  PRODUCTION_BASIN_UNASSIGN_USERS_NOT_AUTHORIZED = ProductionBasinErrorCodes.UNASSIGN_USERS_NOT_AUTHORIZED,
  PRODUCTION_BASIN_UNASSIGN_USERS_FAILED = ProductionBasinErrorCodes.UNASSIGN_USERS_FAILED,
  PRODUCTION_BASIN_STATS_FAILED = ProductionBasinErrorCodes.STATS_FAILED,

  // Campagnes
  CAMPAIGN_NOT_FOUND = CampaignErrorCodes.CAMPAIGN_NOT_FOUND,
  CAMPAIGN_OVERLAP = CampaignErrorCodes.CAMPAIGN_OVERLAP,
  CAMPAIGN_CREATION_FAILED = CampaignErrorCodes.CAMPAIGN_CREATION_FAILED,
  CAMPAIGN_UPDATE_FAILED = CampaignErrorCodes.CAMPAIGN_UPDATE_FAILED,
  CAMPAIGN_ACTIVATION_FAILED = CampaignErrorCodes.CAMPAIGN_ACTIVATION_FAILED,
  CAMPAIGN_DEACTIVATION_FAILED = CampaignErrorCodes.CAMPAIGN_DEACTIVATION_FAILED,
  CAMPAIGN_DEACTIVATION_NOT_ALLOWED = CampaignErrorCodes.CAMPAIGN_DEACTIVATION_NOT_ALLOWED,
  CAMPAIGN_LIST_FAILED = CampaignErrorCodes.CAMPAIGN_LIST_FAILED,
  CAMPAIGN_COUNT_FAILED = CampaignErrorCodes.CAMPAIGN_COUNT_FAILED,
  CAMPAIGN_NOT_AUTHORIZED = CampaignErrorCodes.CAMPAIGN_NOT_AUTHORIZED,
  CAMPAIGN_NO_ACTIVE = CampaignErrorCodes.CAMPAIGN_NO_ACTIVE,
  CAMPAIGN_SYNC_CHECK_FAILED = CampaignErrorCodes.CAMPAIGN_SYNC_CHECK_FAILED,

  // Conventions
  CONVENTION_NOT_FOUND = ConventionErrorCodes.CONVENTION_NOT_FOUND,
  CONVENTION_BUYER_EXPORTER_NOT_FOUND = ConventionErrorCodes.CONVENTION_BUYER_EXPORTER_NOT_FOUND,
  CONVENTION_INVALID_BUYER_EXPORTER_TYPE = ConventionErrorCodes.CONVENTION_INVALID_BUYER_EXPORTER_TYPE,
  CONVENTION_OPA_NOT_FOUND = ConventionErrorCodes.CONVENTION_OPA_NOT_FOUND,
  CONVENTION_INVALID_OPA_TYPE = ConventionErrorCodes.CONVENTION_INVALID_OPA_TYPE,
  CONVENTION_BUYER_EXPORTER_NOT_ACTIVE = ConventionErrorCodes.CONVENTION_BUYER_EXPORTER_NOT_ACTIVE,
  CONVENTION_OPA_NOT_ACTIVE = ConventionErrorCodes.CONVENTION_OPA_NOT_ACTIVE,
  CONVENTION_NO_PRODUCTS = ConventionErrorCodes.CONVENTION_NO_PRODUCTS,
  CONVENTION_CREATE_FAILED = ConventionErrorCodes.CONVENTION_CREATE_FAILED,
  CONVENTION_UPDATE_FAILED = ConventionErrorCodes.CONVENTION_UPDATE_FAILED,
  CONVENTION_STATUS_UPDATE_FAILED = ConventionErrorCodes.CONVENTION_STATUS_UPDATE_FAILED,
  CONVENTION_STATUS_UPDATE_INVALID = ConventionErrorCodes.CONVENTION_STATUS_UPDATE_INVALID,
  CONVENTION_STATUS_MISSING = ConventionErrorCodes.CONVENTION_STATUS_MISSING,
  CONVENTION_DELETE_FAILED = ConventionErrorCodes.CONVENTION_DELETE_FAILED,
  CONVENTION_LIST_FAILED = ConventionErrorCodes.CONVENTION_LIST_FAILED,
  CONVENTION_SHOW_FAILED = ConventionErrorCodes.CONVENTION_SHOW_FAILED,
  CONVENTION_CAMPAIGN_ASSOCIATE_FAILED = ConventionErrorCodes.CONVENTION_CAMPAIGN_ASSOCIATE_FAILED,
  CONVENTION_CAMPAIGN_DISSOCIATE_FAILED = ConventionErrorCodes.CONVENTION_CAMPAIGN_DISSOCIATE_FAILED,
  CONVENTION_CAMPAIGN_NOT_ASSOCIATED = ConventionErrorCodes.CONVENTION_CAMPAIGN_NOT_ASSOCIATED,
  CONVENTION_CAMPAIGN_ID_MISSING = ConventionErrorCodes.CONVENTION_CAMPAIGN_ID_MISSING,
  CONVENTION_ACTIVATE_TO_CAMPAIGN_FAILED = ConventionErrorCodes.CONVENTION_ACTIVATE_TO_CAMPAIGN_FAILED,
  CONVENTION_NO_ACTIVE_CAMPAIGN = ConventionErrorCodes.CONVENTION_NO_ACTIVE_CAMPAIGN,
  CONVENTION_NOT_AUTHORIZED = ConventionErrorCodes.CONVENTION_NOT_AUTHORIZED,
  CONVENTION_SYNC_FAILED = ConventionErrorCodes.CONVENTION_SYNC_FAILED,

  // Magasins
  STORE_NOT_FOUND = StoreErrorCodes.STORE_NOT_FOUND,
  STORE_ID_REQUIRED = StoreErrorCodes.STORE_ID_REQUIRED,
  STORES_LIST_FAILED = StoreErrorCodes.STORES_LIST_FAILED,
  STORE_DETAILS_FAILED = StoreErrorCodes.STORE_DETAILS_FAILED,
  STORE_STATS_FAILED = StoreErrorCodes.STORE_STATS_FAILED,
  STORE_CREATE_FAILED = StoreErrorCodes.STORE_CREATE_FAILED,
  STORE_UPDATE_FAILED = StoreErrorCodes.STORE_UPDATE_FAILED,
  STORE_DELETE_FAILED = StoreErrorCodes.STORE_DELETE_FAILED,
  STORE_CODE_EXISTS = StoreErrorCodes.STORE_CODE_EXISTS,
  STORE_NOT_AUTHORIZED = StoreErrorCodes.STORE_NOT_AUTHORIZED,
  STORE_ACTIVATION_FAILED = StoreErrorCodes.STORE_ACTIVATION_FAILED,
  STORE_DEACTIVATION_FAILED = StoreErrorCodes.STORE_DEACTIVATION_FAILED,
  STORE_ALREADY_ACTIVE = StoreErrorCodes.STORE_ALREADY_ACTIVE,
  STORE_ALREADY_INACTIVE = StoreErrorCodes.STORE_ALREADY_INACTIVE,
  STORE_OCCUPANT_ADD_FAILED = StoreErrorCodes.STORE_OCCUPANT_ADD_FAILED,
  STORE_OCCUPANT_REMOVE_FAILED = StoreErrorCodes.STORE_OCCUPANT_REMOVE_FAILED,
  STORE_OCCUPANTS_FETCH_FAILED = StoreErrorCodes.STORE_OCCUPANTS_FETCH_FAILED,

  // Documents
  DOCUMENT_NOT_FOUND = DocumentErrorCodes.DOCUMENT_NOT_FOUND,
  DOCUMENT_LIST_FAILED = DocumentErrorCodes.DOCUMENT_LIST_FAILED,
  DOCUMENT_CREATION_FAILED = DocumentErrorCodes.DOCUMENT_CREATION_FAILED,
  DOCUMENT_UPDATE_FAILED = DocumentErrorCodes.DOCUMENT_UPDATE_FAILED,
  DOCUMENT_DELETION_FAILED = DocumentErrorCodes.DOCUMENT_DELETION_FAILED,
  DOCUMENT_DOWNLOAD_FAILED = DocumentErrorCodes.DOCUMENT_DOWNLOAD_FAILED,
  DOCUMENT_PREVIEW_FAILED = DocumentErrorCodes.DOCUMENT_PREVIEW_FAILED,
  DOCUMENT_NOT_AUTHORIZED = DocumentErrorCodes.DOCUMENT_NOT_AUTHORIZED,
  DOCUMENT_UPLOAD_FAILED = DocumentErrorCodes.DOCUMENT_UPLOAD_FAILED,
  DOCUMENT_FILE_TOO_LARGE = DocumentErrorCodes.DOCUMENT_FILE_TOO_LARGE,
  DOCUMENT_SYNC_FAILED = DocumentErrorCodes.DOCUMENT_SYNC_FAILED,
  DOCUMENT_FILE_TYPE_NOT_ALLOWED = DocumentErrorCodes.DOCUMENT_FILE_TYPE_NOT_ALLOWED,
  DOCUMENT_FILE_INVALID = DocumentErrorCodes.DOCUMENT_FILE_INVALID,
  DOCUMENT_STORAGE_ERROR = DocumentErrorCodes.DOCUMENT_STORAGE_ERROR,
  DOCUMENT_NOT_PREVIEWABLE = DocumentErrorCodes.DOCUMENT_NOT_PREVIEWABLE,
  DOCUMENT_MINIO_CONNECTION_ERROR = DocumentErrorCodes.DOCUMENT_MINIO_CONNECTION_ERROR,
  DOCUMENT_BUCKET_NOT_FOUND = DocumentErrorCodes.DOCUMENT_BUCKET_NOT_FOUND,
  DOCUMENT_FILE_NOT_FOUND_IN_STORAGE = DocumentErrorCodes.DOCUMENT_FILE_NOT_FOUND_IN_STORAGE,
  DOCUMENT_VALIDATION_FAILED = DocumentErrorCodes.DOCUMENT_VALIDATION_FAILED,
  DOCUMENT_INVALID_FILES = DocumentErrorCodes.DOCUMENT_INVALID_FILES,

  // Transferts de produits
  PRODUCT_TRANSFER_NOT_FOUND = ProductTransferErrorCodes.PRODUCT_TRANSFER_NOT_FOUND,
  PRODUCT_TRANSFER_LIST_FAILED = ProductTransferErrorCodes.PRODUCT_TRANSFER_LIST_FAILED,
  PRODUCT_TRANSFER_CREATE_FAILED = ProductTransferErrorCodes.PRODUCT_TRANSFER_CREATE_FAILED,
  PRODUCT_TRANSFER_UPDATE_FAILED = ProductTransferErrorCodes.PRODUCT_TRANSFER_UPDATE_FAILED,
  PRODUCT_TRANSFER_DELETE_FAILED = ProductTransferErrorCodes.PRODUCT_TRANSFER_DELETE_FAILED,
  PRODUCT_TRANSFER_SHOW_FAILED = ProductTransferErrorCodes.PRODUCT_TRANSFER_SHOW_FAILED,
  PRODUCT_TRANSFER_STATUS_UPDATE_FAILED = ProductTransferErrorCodes.PRODUCT_TRANSFER_STATUS_UPDATE_FAILED,
  PRODUCT_TRANSFER_CODE_EXISTS = ProductTransferErrorCodes.PRODUCT_TRANSFER_CODE_EXISTS,
  PRODUCT_TRANSFER_NOT_AUTHORIZED = ProductTransferErrorCodes.PRODUCT_TRANSFER_NOT_AUTHORIZED,
  PRODUCT_TRANSFER_SENDER_ACTOR_NOT_FOUND = ProductTransferErrorCodes.PRODUCT_TRANSFER_SENDER_ACTOR_NOT_FOUND,
  PRODUCT_TRANSFER_RECEIVER_ACTOR_NOT_FOUND = ProductTransferErrorCodes.PRODUCT_TRANSFER_RECEIVER_ACTOR_NOT_FOUND,
  PRODUCT_TRANSFER_SENDER_STORE_NOT_FOUND = ProductTransferErrorCodes.PRODUCT_TRANSFER_SENDER_STORE_NOT_FOUND,
  PRODUCT_TRANSFER_RECEIVER_STORE_NOT_FOUND = ProductTransferErrorCodes.PRODUCT_TRANSFER_RECEIVER_STORE_NOT_FOUND,
  PRODUCT_TRANSFER_SENDER_STORE_REQUIRED = ProductTransferErrorCodes.PRODUCT_TRANSFER_SENDER_STORE_REQUIRED,
  PRODUCT_TRANSFER_NO_ACTIVE_CAMPAIGN = ProductTransferErrorCodes.PRODUCT_TRANSFER_NO_ACTIVE_CAMPAIGN,
  PRODUCT_TRANSFER_CAMPAIGN_NOT_FOUND = ProductTransferErrorCodes.PRODUCT_TRANSFER_CAMPAIGN_NOT_FOUND,
  PRODUCT_TRANSFER_SENDER_ACTOR_NOT_ACTIVE = ProductTransferErrorCodes.PRODUCT_TRANSFER_SENDER_ACTOR_NOT_ACTIVE,
  PRODUCT_TRANSFER_RECEIVER_ACTOR_NOT_ACTIVE = ProductTransferErrorCodes.PRODUCT_TRANSFER_RECEIVER_ACTOR_NOT_ACTIVE,
  PRODUCT_TRANSFER_SENDER_STORE_NOT_ACTIVE = ProductTransferErrorCodes.PRODUCT_TRANSFER_SENDER_STORE_NOT_ACTIVE,
  PRODUCT_TRANSFER_RECEIVER_STORE_NOT_ACTIVE = ProductTransferErrorCodes.PRODUCT_TRANSFER_RECEIVER_STORE_NOT_ACTIVE,
  PRODUCT_TRANSFER_PRODUCTS_REQUIRED = ProductTransferErrorCodes.PRODUCT_TRANSFER_PRODUCTS_REQUIRED,
  PRODUCT_TRANSFER_NOT_EDITABLE = ProductTransferErrorCodes.PRODUCT_TRANSFER_NOT_EDITABLE,
  PRODUCT_TRANSFER_VALIDATED_LIMITED_EDIT = ProductTransferErrorCodes.PRODUCT_TRANSFER_VALIDATED_LIMITED_EDIT,
  PRODUCT_TRANSFER_INVALID_STATUS_TRANSITION = ProductTransferErrorCodes.PRODUCT_TRANSFER_INVALID_STATUS_TRANSITION,
  PRODUCT_TRANSFER_VALIDATED_NOT_DELETABLE = ProductTransferErrorCodes.PRODUCT_TRANSFER_VALIDATED_NOT_DELETABLE,

  // Synchronisation
  SYNC_CHECK_FAILED = SyncErrorCodes.SYNC_CHECK_FAILED,
  SYNC_PARSE_ERROR = SyncErrorCodes.SYNC_PARSE_ERROR,
  SYNC_DATABASE_ERROR = SyncErrorCodes.SYNC_DATABASE_ERROR,

  // Transactions
  TRANSACTION_NOT_FOUND = TransactionErrorCodes.TRANSACTION_NOT_FOUND,
  TRANSACTION_CREATE_SELLER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_SELLER_NOT_FOUND,
  TRANSACTION_CREATE_BUYER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_BUYER_NOT_FOUND,
  TRANSACTION_CREATE_SELLER_BUYER_SAME = TransactionErrorCodes.TRANSACTION_CREATE_SELLER_BUYER_SAME,
  TRANSACTION_CREATE_CAMPAIGN_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_CAMPAIGN_NOT_FOUND,
  TRANSACTION_CREATE_MARKET_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_MARKET_NOT_FOUND,
  TRANSACTION_CREATE_CONVENTION_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_CONVENTION_NOT_FOUND,
  TRANSACTION_CREATE_PRINCIPAL_EXPORTER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_PRINCIPAL_EXPORTER_NOT_FOUND,
  TRANSACTION_CREATE_COMPLEMENTARY_LIMIT_REACHED = TransactionErrorCodes.TRANSACTION_CREATE_COMPLEMENTARY_LIMIT_REACHED,
  TRANSACTION_CREATE_PRODUCER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_PRODUCER_NOT_FOUND,
  TRANSACTION_CREATE_PRODUCER_REQUIRED_FOR_OPA = TransactionErrorCodes.TRANSACTION_CREATE_PRODUCER_REQUIRED_FOR_OPA,
  TRANSACTION_CREATE_SELLER_NOT_ACTIVE = TransactionErrorCodes.TRANSACTION_CREATE_SELLER_NOT_ACTIVE,
  TRANSACTION_CREATE_BUYER_NOT_ACTIVE = TransactionErrorCodes.TRANSACTION_CREATE_BUYER_NOT_ACTIVE,
  TRANSACTION_CREATE_CALENDAR_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CREATE_CALENDAR_NOT_FOUND,
  TRANSACTION_CREATE_CALENDAR_NOT_ACTIVE = TransactionErrorCodes.TRANSACTION_CREATE_CALENDAR_NOT_ACTIVE,
  TRANSACTION_CREATE_CONVENTION_NOT_ACTIVE = TransactionErrorCodes.TRANSACTION_CREATE_CONVENTION_NOT_ACTIVE,
  TRANSACTION_CONFIRM_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CONFIRM_NOT_FOUND,
  TRANSACTION_CONFIRM_NOT_PENDING = TransactionErrorCodes.TRANSACTION_CONFIRM_NOT_PENDING,
  TRANSACTION_CANCEL_NOT_FOUND = TransactionErrorCodes.TRANSACTION_CANCEL_NOT_FOUND,
  TRANSACTION_UPDATE_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_NOT_FOUND,
  TRANSACTION_UPDATE_NOT_PENDING = TransactionErrorCodes.TRANSACTION_UPDATE_NOT_PENDING,
  TRANSACTION_UPDATE_SELLER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_SELLER_NOT_FOUND,
  TRANSACTION_UPDATE_BUYER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_BUYER_NOT_FOUND,
  TRANSACTION_UPDATE_CALENDAR_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_CALENDAR_NOT_FOUND,
  TRANSACTION_UPDATE_CONVENTION_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_CONVENTION_NOT_FOUND,
  TRANSACTION_DELETE_NOT_FOUND = TransactionErrorCodes.TRANSACTION_DELETE_NOT_FOUND,
  TRANSACTION_LIST_FAILED = TransactionErrorCodes.TRANSACTION_LIST_FAILED,
  TRANSACTION_CREATION_FAILED = TransactionErrorCodes.TRANSACTION_CREATION_FAILED,
  TRANSACTION_UPDATE_FAILED = TransactionErrorCodes.TRANSACTION_UPDATE_FAILED,
  TRANSACTION_CONFIRM_FAILED = TransactionErrorCodes.TRANSACTION_CONFIRM_FAILED,
  TRANSACTION_CANCEL_FAILED = TransactionErrorCodes.TRANSACTION_CANCEL_FAILED,
  TRANSACTION_DELETE_FAILED = TransactionErrorCodes.TRANSACTION_DELETE_FAILED,
  TRANSACTION_UPDATE_PRODUCTS_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_PRODUCTS_NOT_FOUND,
  TRANSACTION_UPDATE_PRODUCTS_NOT_PENDING = TransactionErrorCodes.TRANSACTION_UPDATE_PRODUCTS_NOT_PENDING,
  TRANSACTION_UPDATE_PRODUCTS_FAILED = TransactionErrorCodes.TRANSACTION_UPDATE_PRODUCTS_FAILED,
  TRANSACTION_UPDATE_PRODUCTS_PRODUCER_REQUIRED_FOR_OPA = TransactionErrorCodes.TRANSACTION_UPDATE_PRODUCTS_PRODUCER_REQUIRED_FOR_OPA,
  TRANSACTION_UPDATE_PRODUCTS_PRODUCER_NOT_FOUND = TransactionErrorCodes.TRANSACTION_UPDATE_PRODUCTS_PRODUCER_NOT_FOUND,
}

/**
 * Enum unifié des codes de succès pour la compatibilité avec l'ancien système
 */
export enum SuccessCodes {
  // Acteurs
  ACTOR_LIST_SUCCESS = ActorSuccessCodes.ACTOR_LIST_SUCCESS,
  ACTOR_FETCH_SUCCESS = ActorSuccessCodes.ACTOR_FETCH_SUCCESS,
  ACTOR_CREATED = ActorSuccessCodes.ACTOR_CREATED,
  ACTOR_UPDATED = ActorSuccessCodes.ACTOR_UPDATED,
  ACTOR_DELETED = ActorSuccessCodes.ACTOR_DELETED,
  ACTOR_ACTIVATED = ActorSuccessCodes.ACTOR_ACTIVATED,
  ACTOR_DEACTIVATED = ActorSuccessCodes.ACTOR_DEACTIVATED,
  ACTOR_STATUS_UPDATED = ActorSuccessCodes.ACTOR_STATUS_UPDATED,
  PRODUCER_ADDED_TO_OPA = ActorSuccessCodes.PRODUCER_ADDED_TO_OPA,
  PRODUCER_REMOVED_FROM_OPA = ActorSuccessCodes.PRODUCER_REMOVED_FROM_OPA,
  BUYER_ADDED_TO_EXPORTER = ActorSuccessCodes.BUYER_ADDED_TO_EXPORTER,
  BUYER_REMOVED_FROM_EXPORTER = ActorSuccessCodes.BUYER_REMOVED_FROM_EXPORTER,
  ACTOR_SYNC_SUCCESS = ActorSuccessCodes.ACTOR_SYNC_SUCCESS,

  // Audit Logs
  AUDIT_LOG_LIST_SUCCESS = AuditLogSuccessCodes.AUDIT_LOG_LIST_SUCCESS,
  AUDIT_LOG_DETAILS_SUCCESS = AuditLogSuccessCodes.AUDIT_LOG_DETAILS_SUCCESS,
  AUDIT_LOG_STATS_SUCCESS = AuditLogSuccessCodes.AUDIT_LOG_STATS_SUCCESS,

  // Authentification
  AUTH_LOGIN_SUCCESS = AuthSuccessCodes.LOGIN_SUCCESS,
  AUTH_LOGIN_OTP_SENT = AuthSuccessCodes.LOGIN_OTP_SENT,
  AUTH_OTP_VERIFIED = AuthSuccessCodes.OTP_VERIFIED,
  AUTH_LOGOUT_SUCCESS = AuthSuccessCodes.LOGOUT_SUCCESS,
  AUTH_PASSWORD_CHANGED = AuthSuccessCodes.PASSWORD_CHANGED,
  AUTH_PASSWORD_RESET_EMAIL_SENT = AuthSuccessCodes.PASSWORD_RESET_EMAIL_SENT,
  AUTH_PASSWORD_RESET_SUCCESS = AuthSuccessCodes.PASSWORD_RESET_SUCCESS,
  AUTH_ACCOUNT_INITIALIZED = AuthSuccessCodes.ACCOUNT_INITIALIZED,
  AUTH_ACCOUNT_TO_BE_INITIALIZED = AuthSuccessCodes.ACCOUNT_TO_BE_INITIALIZED,
  AUTH_SECURITY_QUESTIONS_SETUP = AuthSuccessCodes.SECURITY_QUESTIONS_SETUP,

  // Calendriers
  CALENDAR_CREATED = CalendarSuccessCodes.CREATED,
  CALENDAR_UPDATED = CalendarSuccessCodes.UPDATED,
  CALENDAR_STATUS_UPDATED = CalendarSuccessCodes.STATUS_UPDATED,
  CALENDAR_EXPECTED_SALES_COUNT_UPDATED = CalendarSuccessCodes.EXPECTED_SALES_COUNT_UPDATED,
  CALENDAR_DELETED = CalendarSuccessCodes.DELETED,
  CALENDAR_LIST_SUCCESS = CalendarSuccessCodes.LIST_SUCCESS,
  CALENDAR_DETAILS_SUCCESS = CalendarSuccessCodes.DETAILS_SUCCESS,
  CALENDAR_AUDIT_HISTORY_SUCCESS = CalendarSuccessCodes.AUDIT_HISTORY_SUCCESS,
  CALENDAR_SYNC_SUCCESS = CalendarSuccessCodes.SYNC_SUCCESS,

  // Utilisateurs
  USER_CREATED = UserSuccessCodes.CREATED,
  USER_UPDATED = UserSuccessCodes.UPDATED,
  USER_STATUS_UPDATED = UserSuccessCodes.STATUS_UPDATED,
  USER_PASSWORD_RESET = UserSuccessCodes.PASSWORD_RESET,
  USER_DELETED = UserSuccessCodes.DELETED,
  USER_LIST_SUCCESS = UserSuccessCodes.LIST_SUCCESS,
  USER_DETAILS_SUCCESS = UserSuccessCodes.DETAILS_SUCCESS,
  USER_AUDIT_HISTORY_SUCCESS = UserSuccessCodes.AUDIT_HISTORY_SUCCESS,

  // Localisations
  LOCATION_LIST_SUCCESS = LocationSuccessCodes.LIST_SUCCESS,
  LOCATION_HIERARCHY_SUCCESS = LocationSuccessCodes.HIERARCHY_SUCCESS,
  LOCATION_CHILDREN_SUCCESS = LocationSuccessCodes.CHILDREN_SUCCESS,

  // Parcelles
  PARCEL_LIST_SUCCESS = ParcelSuccessCodes.PARCEL_LIST_SUCCESS,
  PARCEL_FETCH_SUCCESS = ParcelSuccessCodes.PARCEL_FETCH_SUCCESS,
  PARCEL_CREATED = ParcelSuccessCodes.PARCEL_CREATED,
  PARCEL_UPDATED = ParcelSuccessCodes.PARCEL_UPDATED,
  PARCEL_DELETED = ParcelSuccessCodes.PARCEL_DELETED,
  PARCEL_ACTIVATED = ParcelSuccessCodes.PARCEL_ACTIVATED,
  PARCEL_DEACTIVATED = ParcelSuccessCodes.PARCEL_DEACTIVATED,
  PARCEL_COORDINATES_ADDED = ParcelSuccessCodes.PARCEL_COORDINATES_ADDED,
  PARCEL_COORDINATES_UPDATED = ParcelSuccessCodes.PARCEL_COORDINATES_UPDATED,
  PARCEL_COORDINATES_REMOVED = ParcelSuccessCodes.PARCEL_COORDINATES_REMOVED,
  PARCEL_STATS_SUCCESS = ParcelSuccessCodes.PARCEL_STATS_SUCCESS,

  // Bassins de production
  PRODUCTION_BASIN_LIST_SUCCESS = ProductionBasinSuccessCodes.LIST_SUCCESS,
  PRODUCTION_BASIN_CREATED = ProductionBasinSuccessCodes.CREATED,
  PRODUCTION_BASIN_UPDATED = ProductionBasinSuccessCodes.UPDATED,
  PRODUCTION_BASIN_DELETED = ProductionBasinSuccessCodes.DELETED,
  PRODUCTION_BASIN_USERS_ASSIGNED = ProductionBasinSuccessCodes.USERS_ASSIGNED,
  PRODUCTION_BASIN_USERS_UNASSIGNED = ProductionBasinSuccessCodes.USERS_UNASSIGNED,
  PRODUCTION_BASIN_STATS_SUCCESS = ProductionBasinSuccessCodes.STATS_SUCCESS,

  // Campagnes
  CAMPAIGN_CREATED = CampaignSuccessCodes.CAMPAIGN_CREATED,
  CAMPAIGN_UPDATED = CampaignSuccessCodes.CAMPAIGN_UPDATED,
  CAMPAIGN_ACTIVATED = CampaignSuccessCodes.CAMPAIGN_ACTIVATED,
  CAMPAIGN_DEACTIVATED = CampaignSuccessCodes.CAMPAIGN_DEACTIVATED,
  CAMPAIGN_LIST_SUCCESS = CampaignSuccessCodes.CAMPAIGN_LIST_SUCCESS,
  CAMPAIGN_FETCH_SUCCESS = CampaignSuccessCodes.CAMPAIGN_FETCH_SUCCESS,
  CAMPAIGN_COUNT_SUCCESS = CampaignSuccessCodes.CAMPAIGN_COUNT_SUCCESS,
  CAMPAIGN_SYNC_CHECK_SUCCESS = CampaignSuccessCodes.CAMPAIGN_SYNC_CHECK_SUCCESS,

  // Conventions
  CONVENTION_CREATED = ConventionSuccessCodes.CONVENTION_CREATED,
  CONVENTION_UPDATED = ConventionSuccessCodes.CONVENTION_UPDATED,
  CONVENTION_STATUS_UPDATED = ConventionSuccessCodes.CONVENTION_STATUS_UPDATED,
  CONVENTION_STATUS_UPDATE_SUCCESS = ConventionSuccessCodes.CONVENTION_STATUS_UPDATE_SUCCESS,
  CONVENTION_DELETED = ConventionSuccessCodes.CONVENTION_DELETED,
  CONVENTION_DELETE_SUCCESS = ConventionSuccessCodes.CONVENTION_DELETE_SUCCESS,
  CONVENTION_LIST_SUCCESS = ConventionSuccessCodes.CONVENTION_LIST_SUCCESS,
  CONVENTION_SHOW_SUCCESS = ConventionSuccessCodes.CONVENTION_SHOW_SUCCESS,
  CONVENTION_UPDATE_SUCCESS = ConventionSuccessCodes.CONVENTION_UPDATE_SUCCESS,
  CONVENTION_CAMPAIGN_ASSOCIATE_SUCCESS = ConventionSuccessCodes.CONVENTION_CAMPAIGN_ASSOCIATE_SUCCESS,
  CONVENTION_CAMPAIGN_DISSOCIATE_SUCCESS = ConventionSuccessCodes.CONVENTION_CAMPAIGN_DISSOCIATE_SUCCESS,
  CONVENTION_ACTIVATE_TO_CAMPAIGN_SUCCESS = ConventionSuccessCodes.CONVENTION_ACTIVATE_TO_CAMPAIGN_SUCCESS,
  CONVENTION_SYNC_SUCCESS = ConventionSuccessCodes.CONVENTION_SYNC_SUCCESS,

  // Magasins
  STORES_LIST_SUCCESS = StoreSuccessCodes.STORES_LIST_SUCCESS,
  STORE_DETAILS_SUCCESS = StoreSuccessCodes.STORE_DETAILS_SUCCESS,
  STORE_STATS_SUCCESS = StoreSuccessCodes.STORE_STATS_SUCCESS,
  STORE_CREATED = StoreSuccessCodes.STORE_CREATED,
  STORE_UPDATED = StoreSuccessCodes.STORE_UPDATED,
  STORE_DELETED = StoreSuccessCodes.STORE_DELETED,
  STORE_STATUS_UPDATED = StoreSuccessCodes.STORE_STATUS_UPDATED,
  STORE_ACTIVATED = StoreSuccessCodes.STORE_ACTIVATED,
  STORE_DEACTIVATED = StoreSuccessCodes.STORE_DEACTIVATED,
  STORE_OCCUPANT_ADDED = StoreSuccessCodes.STORE_OCCUPANT_ADDED,
  STORE_OCCUPANT_REMOVED = StoreSuccessCodes.STORE_OCCUPANT_REMOVED,
  STORE_OCCUPANTS_FETCH_SUCCESS = StoreSuccessCodes.STORE_OCCUPANTS_FETCH_SUCCESS,

  // Documents
  DOCUMENT_LIST_SUCCESS = DocumentSuccessCodes.DOCUMENT_LIST_SUCCESS,
  DOCUMENT_FETCH_SUCCESS = DocumentSuccessCodes.DOCUMENT_FETCH_SUCCESS,
  DOCUMENT_CREATED = DocumentSuccessCodes.DOCUMENT_CREATED,
  DOCUMENT_UPDATED = DocumentSuccessCodes.DOCUMENT_UPDATED,
  DOCUMENT_DELETED = DocumentSuccessCodes.DOCUMENT_DELETED,
  DOCUMENT_DOWNLOADED = DocumentSuccessCodes.DOCUMENT_DOWNLOADED,
  DOCUMENT_PREVIEWED = DocumentSuccessCodes.DOCUMENT_PREVIEWED,
  DOCUMENT_UPLOADED = DocumentSuccessCodes.DOCUMENT_UPLOADED,
  DOCUMENTS_FETCHED = DocumentSuccessCodes.DOCUMENTS_FETCHED,
  DOCUMENT_SYNC_SUCCESS = DocumentSuccessCodes.DOCUMENT_SYNC_SUCCESS,

  // Transferts de produits
  PRODUCT_TRANSFER_LIST_SUCCESS = ProductTransferSuccessCodes.PRODUCT_TRANSFER_LIST_SUCCESS,
  PRODUCT_TRANSFER_CREATE_SUCCESS = ProductTransferSuccessCodes.PRODUCT_TRANSFER_CREATE_SUCCESS,
  PRODUCT_TRANSFER_UPDATE_SUCCESS = ProductTransferSuccessCodes.PRODUCT_TRANSFER_UPDATE_SUCCESS,
  PRODUCT_TRANSFER_DELETE_SUCCESS = ProductTransferSuccessCodes.PRODUCT_TRANSFER_DELETE_SUCCESS,
  PRODUCT_TRANSFER_SHOW_SUCCESS = ProductTransferSuccessCodes.PRODUCT_TRANSFER_SHOW_SUCCESS,
  PRODUCT_TRANSFER_STATUS_UPDATE_SUCCESS = ProductTransferSuccessCodes.PRODUCT_TRANSFER_STATUS_UPDATE_SUCCESS,

  // Synchronisation
  SYNC_CHECK_SUCCESS = SyncSuccessCodes.SYNC_CHECK_SUCCESS,

  // Transactions
  TRANSACTION_LIST_SUCCESS = TransactionSuccessCodes.TRANSACTION_LIST_SUCCESS,
  TRANSACTION_CREATE_SUCCESS = TransactionSuccessCodes.TRANSACTION_CREATE_SUCCESS,
  TRANSACTION_SHOW_SUCCESS = TransactionSuccessCodes.TRANSACTION_SHOW_SUCCESS,
  TRANSACTION_UPDATE_SUCCESS = TransactionSuccessCodes.TRANSACTION_UPDATE_SUCCESS,
  TRANSACTION_CONFIRM_SUCCESS = TransactionSuccessCodes.TRANSACTION_CONFIRM_SUCCESS,
  TRANSACTION_CANCEL_SUCCESS = TransactionSuccessCodes.TRANSACTION_CANCEL_SUCCESS,
  TRANSACTION_DELETE_SUCCESS = TransactionSuccessCodes.TRANSACTION_DELETE_SUCCESS,
  TRANSACTION_COMPLEMENTARY_SUCCESS = TransactionSuccessCodes.TRANSACTION_COMPLEMENTARY_SUCCESS,
  TRANSACTION_UPDATE_PRODUCTS_SUCCESS = TransactionSuccessCodes.TRANSACTION_UPDATE_PRODUCTS_SUCCESS,
}

// Import des messages pour créer les objets unifiés
import { ActorErrorMessages, ActorSuccessMessages } from './actor.js'
import { AuditLogErrorMessages, AuditLogSuccessMessages } from './audit_log.js'
import { AuthErrorMessages, AuthSuccessMessages } from './auth.js'
import { CampaignErrorMessages, CampaignSuccessMessages } from './campaign.js'
import { DocumentErrorMessages, DocumentSuccessMessages } from './document.js'
import { LocationErrorMessages, LocationSuccessMessages } from './location.js'
import { ParcelErrorMessages, ParcelSuccessMessages } from './parcel.js'
import { ProductTransferErrorMessages, ProductTransferSuccessMessages } from './product_transfer.js'
import { ProductionBasinErrorMessages, ProductionBasinSuccessMessages } from './production_basin.js'
import { StoreErrorMessages, StoreSuccessMessages } from './store.js'
import { SyncErrorMessages, SyncSuccessMessages } from './sync.js'
import { SystemErrorMessages } from './system.js'
import { TransactionErrorMessages, TransactionSuccessMessages } from './transaction.js'
import { UserErrorMessages, UserSuccessMessages } from './user.js'
import { ValidationErrorMessages } from './validation.js'

/**
 * Messages d'erreur unifiés pour la compatibilité
 */
export const ErrorMessages: Record<ErrorCodes, string> = {
  ...Object.fromEntries(
    Object.entries(ActorErrorMessages).map(([key, value]) => [
      `ACTOR_${key.replace('ACTOR_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(AuditLogErrorMessages).map(([key, value]) => [
      `AUDIT_LOG_${key.replace('AUDIT_LOG_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(AuthErrorMessages).map(([key, value]) => [
      `AUTH_${key.replace('AUTH_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(UserErrorMessages).map(([key, value]) => [
      `USER_${key.replace('USER_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ValidationErrorMessages).map(([key, value]) => [
      `VALIDATION_${key.replace('VALIDATION_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(SystemErrorMessages).map(([key, value]) => [
      `SYSTEM_${key.replace('SYSTEM_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(LocationErrorMessages).map(([key, value]) => [
      `LOCATION_${key.replace('LOCATION_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ParcelErrorMessages).map(([key, value]) => [
      `PARCEL_${key.replace('PARCEL_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ProductionBasinErrorMessages).map(([key, value]) => [
      `PRODUCTION_BASIN_${key.replace('PRODUCTION_BASIN_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(CampaignErrorMessages).map(([key, value]) => [
      `CAMPAIGN_${key.replace('CAMPAIGN_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(StoreErrorMessages).map(([key, value]) => [
      `STORE_${key.replace('STORE_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(DocumentErrorMessages).map(([key, value]) => [
      `DOCUMENT_${key.replace('DOCUMENT_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ProductTransferErrorMessages).map(([key, value]) => [
      `PRODUCT_TRANSFER_${key.replace('PRODUCT_TRANSFER_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(SyncErrorMessages).map(([key, value]) => [
      `SYNC_${key.replace('SYNC_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(TransactionErrorMessages).map(([key, value]) => [
      `TRANSACTION_${key.replace('TRANSACTION_', '')}`,
      value,
    ])
  ),
} as Record<ErrorCodes, string>

/**
 * Messages de succès unifiés pour la compatibilité
 */
export const SuccessMessages: Record<SuccessCodes, string> = {
  ...Object.fromEntries(
    Object.entries(ActorSuccessMessages).map(([key, value]) => [
      `ACTOR_${key.replace('ACTOR_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(AuditLogSuccessMessages).map(([key, value]) => [
      `AUDIT_LOG_${key.replace('AUDIT_LOG_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(AuthSuccessMessages).map(([key, value]) => [
      `AUTH_${key.replace('AUTH_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(UserSuccessMessages).map(([key, value]) => [
      `USER_${key.replace('USER_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(LocationSuccessMessages).map(([key, value]) => [
      `LOCATION_${key.replace('LOCATION_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ParcelSuccessMessages).map(([key, value]) => [
      `PARCEL_${key.replace('PARCEL_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ProductionBasinSuccessMessages).map(([key, value]) => [
      `PRODUCTION_BASIN_${key.replace('PRODUCTION_BASIN_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(CampaignSuccessMessages).map(([key, value]) => [
      `CAMPAIGN_${key.replace('CAMPAIGN_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(StoreSuccessMessages).map(([key, value]) => [
      `STORE_${key.replace('STORE_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(DocumentSuccessMessages).map(([key, value]) => [
      `DOCUMENT_${key.replace('DOCUMENT_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(ProductTransferSuccessMessages).map(([key, value]) => [
      `PRODUCT_TRANSFER_${key.replace('PRODUCT_TRANSFER_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(SyncSuccessMessages).map(([key, value]) => [
      `SYNC_${key.replace('SYNC_', '')}`,
      value,
    ])
  ),
  ...Object.fromEntries(
    Object.entries(TransactionSuccessMessages).map(([key, value]) => [
      `TRANSACTION_${key.replace('TRANSACTION_', '')}`,
      value,
    ])
  ),
} as Record<SuccessCodes, string>
