export const TRANSACTION_SUCCESS_CODES = {
  LIST_SUCCESS: "TRANSACTION_LIST_SUCCESS",
  CREATE_SUCCESS: "TRANSACTION_CREATE_SUCCESS",
  SHOW_SUCCESS: "TRANSACTION_SHOW_SUCCESS",
  UPDATE_SUCCESS: "TRANSACTION_UPDATE_SUCCESS",
  CONFIRM_SUCCESS: "TRANSACTION_CONFIRM_SUCCESS",
  CANCEL_SUCCESS: "TRANSACTION_CANCEL_SUCCESS",
  DELETE_SUCCESS: "TRANSACTION_DELETE_SUCCESS",
  COMPLEMENTARY_SUCCESS: "TRANSACTION_COMPLEMENTARY_SUCCESS",
} as const;

export const TRANSACTION_ERROR_CODES = {
  LIST_FAILED: "TRANSACTION_LIST_FAILED",
  CREATION_FAILED: "TRANSACTION_CREATION_FAILED",
  CREATE_SELLER_NOT_FOUND: "TRANSACTION_CREATE_SELLER_NOT_FOUND",
  CREATE_BUYER_NOT_FOUND: "TRANSACTION_CREATE_BUYER_NOT_FOUND",
  CREATE_SELLER_BUYER_SAME: "TRANSACTION_CREATE_SELLER_BUYER_SAME",
  CREATE_CAMPAIGN_NOT_FOUND: "TRANSACTION_CREATE_CAMPAIGN_NOT_FOUND",
  CREATE_PRODUCER_REQUIRED_FOR_OPA: "TRANSACTION_CREATE_PRODUCER_REQUIRED_FOR_OPA",
  CREATE_PRODUCER_NOT_FOUND: "TRANSACTION_CREATE_PRODUCER_NOT_FOUND",
  CREATE_COMPLEMENTARY_LIMIT_REACHED:
    "TRANSACTION_CREATE_COMPLEMENTARY_LIMIT_REACHED",
  NOT_FOUND: "TRANSACTION_NOT_FOUND",
  UPDATE_FAILED: "TRANSACTION_UPDATE_FAILED",
  CONFIRM_NOT_FOUND: "TRANSACTION_CONFIRM_NOT_FOUND",
  CONFIRM_NOT_PENDING: "TRANSACTION_CONFIRM_NOT_PENDING",
  CONFIRM_FAILED: "TRANSACTION_CONFIRM_FAILED",
  CANCEL_FAILED: "TRANSACTION_CANCEL_FAILED",
  DELETE_FAILED: "TRANSACTION_DELETE_FAILED",
} as const;
