/**
 * Codes d'erreur pour la feature Calendar
 */
export const CalendarErrorCodes = {
  // Codes génériques
  CALENDAR_NOT_FOUND: "CALENDAR_NOT_FOUND",
  CALENDAR_LIST_ERROR: "CALENDAR_LIST_ERROR",
  CALENDAR_CREATE_ERROR: "CALENDAR_CREATE_ERROR",
  CALENDAR_UPDATE_ERROR: "CALENDAR_UPDATE_ERROR",
  CALENDAR_DELETE_ERROR: "CALENDAR_DELETE_ERROR",
  CALENDAR_FETCH_ERROR: "CALENDAR_FETCH_ERROR",
  CALENDAR_VALIDATION_ERROR: "CALENDAR_VALIDATION_ERROR",
  CALENDAR_PERMISSION_ERROR: "CALENDAR_PERMISSION_ERROR",

  // Codes spécifiques - Liste
  CALENDAR_LIST_FAILED: "CALENDAR_LIST_FAILED",

  // Codes spécifiques - Création
  CALENDAR_CREATE_FAILED: "CALENDAR_CREATE_FAILED",
  CAMPAIGN_NOT_FOUND: "CAMPAIGN_NOT_FOUND",
  CONVENTION_REQUIRED: "CONVENTION_REQUIRED",
  CONVENTION_NOT_FOUND: "CONVENTION_NOT_FOUND",
  CODE_EXISTS: "CODE_EXISTS",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",

  // Codes spécifiques - Récupération
  CALENDAR_SHOW_FAILED: "CALENDAR_SHOW_FAILED",

  // Codes spécifiques - Mise à jour
  CALENDAR_UPDATE_FAILED: "CALENDAR_UPDATE_FAILED",
  CALENDAR_UPDATE_NOT_AUTHORIZED: "CALENDAR_UPDATE_NOT_AUTHORIZED",
  CALENDAR_STATUS_UPDATE_INVALID: "CALENDAR_STATUS_UPDATE_INVALID",
  CALENDAR_STATUS_UPDATE_FAILED: "CALENDAR_STATUS_UPDATE_FAILED",

  // Codes spécifiques - Suppression
  CALENDAR_DELETE_NOT_AUTHORIZED: "CALENDAR_DELETE_NOT_AUTHORIZED",
  CALENDAR_DELETE_FAILED: "CALENDAR_DELETE_FAILED",
} as const;

/**
 * Codes de succès pour la feature Calendar
 */
export const CalendarSuccessCodes = {
  CALENDAR_LIST_SUCCESS: "CALENDAR_LIST_SUCCESS",
  CALENDAR_FETCH_SUCCESS: "CALENDAR_FETCH_SUCCESS",
  CALENDAR_CREATE_SUCCESS: "CALENDAR_CREATE_SUCCESS",
  CALENDAR_UPDATE_SUCCESS: "CALENDAR_UPDATE_SUCCESS",
  CALENDAR_DELETE_SUCCESS: "CALENDAR_DELETE_SUCCESS",
  CALENDAR_CREATED: "CALENDAR_CREATED",
  CALENDAR_UPDATED: "CALENDAR_UPDATED",
  CALENDAR_STATUS_UPDATED: "CALENDAR_STATUS_UPDATED",
  CALENDAR_DELETED: "CALENDAR_DELETED",
  CALENDAR_DETAILS_SUCCESS: "CALENDAR_DETAILS_SUCCESS",
} as const;

export type CalendarErrorCode = keyof typeof CalendarErrorCodes;
export type CalendarSuccessCode = keyof typeof CalendarSuccessCodes;
