/**
 * Codes d'erreur pour la feature Product Transfer
 */
export const ProductTransferErrorCodes = {
  // Codes génériques
  PRODUCT_TRANSFER_NOT_FOUND: "PRODUCT_TRANSFER_NOT_FOUND",
  PRODUCT_TRANSFER_LIST_ERROR: "PRODUCT_TRANSFER_LIST_ERROR",
  PRODUCT_TRANSFER_CREATE_ERROR: "PRODUCT_TRANSFER_CREATE_ERROR",
  PRODUCT_TRANSFER_UPDATE_ERROR: "PRODUCT_TRANSFER_UPDATE_ERROR",
  PRODUCT_TRANSFER_DELETE_ERROR: "PRODUCT_TRANSFER_DELETE_ERROR",
  PRODUCT_TRANSFER_FETCH_ERROR: "PRODUCT_TRANSFER_FETCH_ERROR",
  PRODUCT_TRANSFER_VALIDATION_ERROR: "PRODUCT_TRANSFER_VALIDATION_ERROR",
  PRODUCT_TRANSFER_PERMISSION_ERROR: "PRODUCT_TRANSFER_PERMISSION_ERROR",

  // Codes spécifiques - Création
  PRODUCT_TRANSFER_CREATE_FAILED: "PRODUCT_TRANSFER_CREATE_FAILED",
  PRODUCT_TRANSFER_SENDER_ACTOR_NOT_FOUND: "PRODUCT_TRANSFER_SENDER_ACTOR_NOT_FOUND",
  PRODUCT_TRANSFER_RECEIVER_ACTOR_NOT_FOUND: "PRODUCT_TRANSFER_RECEIVER_ACTOR_NOT_FOUND",
  PRODUCT_TRANSFER_SENDER_STORE_NOT_FOUND: "PRODUCT_TRANSFER_SENDER_STORE_NOT_FOUND",
  PRODUCT_TRANSFER_RECEIVER_STORE_NOT_FOUND: "PRODUCT_TRANSFER_RECEIVER_STORE_NOT_FOUND",
  PRODUCT_TRANSFER_CAMPAIGN_NOT_FOUND: "PRODUCT_TRANSFER_CAMPAIGN_NOT_FOUND",
  PRODUCT_TRANSFER_INVALID_TRANSFER_TYPE: "PRODUCT_TRANSFER_INVALID_TRANSFER_TYPE",
  PRODUCT_TRANSFER_INVALID_PRODUCTS: "PRODUCT_TRANSFER_INVALID_PRODUCTS",
  PRODUCT_TRANSFER_DRIVER_INFO_REQUIRED: "PRODUCT_TRANSFER_DRIVER_INFO_REQUIRED",

  // Codes spécifiques - Récupération
  PRODUCT_TRANSFER_LIST_FAILED: "PRODUCT_TRANSFER_LIST_FAILED",

  // Codes spécifiques - Mise à jour
  PRODUCT_TRANSFER_UPDATE_FAILED: "PRODUCT_TRANSFER_UPDATE_FAILED",
  PRODUCT_TRANSFER_UPDATE_NOT_AUTHORIZED: "PRODUCT_TRANSFER_UPDATE_NOT_AUTHORIZED",
  PRODUCT_TRANSFER_STATUS_UPDATE_INVALID: "PRODUCT_TRANSFER_STATUS_UPDATE_INVALID",
  PRODUCT_TRANSFER_STATUS_UPDATE_FAILED: "PRODUCT_TRANSFER_STATUS_UPDATE_FAILED",

  // Codes spécifiques - Suppression
  PRODUCT_TRANSFER_DELETE_NOT_AUTHORIZED: "PRODUCT_TRANSFER_DELETE_NOT_AUTHORIZED",
  PRODUCT_TRANSFER_DELETE_FAILED: "PRODUCT_TRANSFER_DELETE_FAILED",
} as const;

/**
 * Codes de succès pour la feature Product Transfer
 */
export const ProductTransferSuccessCodes = {
  PRODUCT_TRANSFER_LIST_SUCCESS: "PRODUCT_TRANSFER_LIST_SUCCESS",
  PRODUCT_TRANSFER_FETCH_SUCCESS: "PRODUCT_TRANSFER_FETCH_SUCCESS",
  PRODUCT_TRANSFER_CREATE_SUCCESS: "PRODUCT_TRANSFER_CREATE_SUCCESS",
  PRODUCT_TRANSFER_UPDATE_SUCCESS: "PRODUCT_TRANSFER_UPDATE_SUCCESS",
  PRODUCT_TRANSFER_DELETE_SUCCESS: "PRODUCT_TRANSFER_DELETE_SUCCESS",
  PRODUCT_TRANSFER_CREATED: "PRODUCT_TRANSFER_CREATED",
  PRODUCT_TRANSFER_UPDATED: "PRODUCT_TRANSFER_UPDATED",
  PRODUCT_TRANSFER_STATUS_UPDATED: "PRODUCT_TRANSFER_STATUS_UPDATED",
  PRODUCT_TRANSFER_DELETED: "PRODUCT_TRANSFER_DELETED",
  PRODUCT_TRANSFER_DETAILS_SUCCESS: "PRODUCT_TRANSFER_DETAILS_SUCCESS",
} as const;

export type ProductTransferErrorCode = keyof typeof ProductTransferErrorCodes;
export type ProductTransferSuccessCode = keyof typeof ProductTransferSuccessCodes;
